# attribute_patterns.py

id_pattern = r"ID: (.+?)(?=(?:ID:|$))"
name_pattern = r"Name: (.+?)(?=(?:Name:|$))"
supertype_pattern = r"Supertype: (.+?)(?=(?:Supertype:|$))"
subtypes_pattern = r"Subtypes: (.+?)(?=(?:Subtypes:|$))"
hp_pattern = r"HP: (.+?)(?=(?:HP:|$))"
types_pattern = r"Types: (.+?)(?=(?:Types:|$))"
evolves_from_pattern = r"Evolves From: (.+?)(?=(?:Evolves From:|$))"
evolves_to_pattern = r"Evolves To: (.+?)(?=(?:Evolves To:|$))"
rules_list_pattern = r"Rules List: (.+?)(?=(?:Rules List:|$))"
ancient_trait_name_pattern = r"Ancient Trait Name: (.+?)(?=(?:Ancient Trait Name:|$))"
ancient_trait_text_pattern = r"Ancient Trait Text: (.+?)(?=(?:Ancient Trait Text:|$))"
abilities_name_pattern = r"Ability Name: (.+?)(?=(?:Ability Name:|$))"
abilities_text_pattern = r"Ability Text: (.+?)(?=(?:Ability Text:|$))"
abilities_type_pattern = r"Ability Type: (.+?)(?=(?:Ability Type:|$))"
attacks_name_pattern = r"Attack Name: (.+?)(?=(?:Attack Name:|$))"
attacks_cost_pattern = r"Attack Cost: (.+?)(?=(?:Attack Cost:|$))"
attacks_converted_energy_cost_pattern = r"Attack Converted Energy Cost: (.+?)(?=(?:Attack Converted Energy Cost:|$))"
attacks_damage_pattern = r"Attack Damage: (.+?)(?=(?:Attack Damage:|$))"
attacks_text_pattern = r"Attack Text: (.+?)(?=(?:Attack Text:|$))"
weaknesses_type_pattern = r"Weakness Type: (.+?)(?=(?:Weakness Type:|$))"
weaknesses_value_pattern = r"Weakness Value: (.+?)(?=(?:Weakness Value:|$))"
resistances_type_pattern = r"Resistance Type: (.+?)(?=(?:Resistance Type:|$))"
resistances_value_pattern = r"Resistance Value: (.+?)(?=(?:Resistance Value:|$))"
retreat_cost_pattern = r"Retreat Cost: (.+?)(?=(?:Retreat Cost:|$))"
converted_retreat_cost_pattern = r"Converted Retreat Cost: (.+?)(?=(?:Converted Retreat Cost:|$))"
card_set_id_pattern = r"Card Set ID: (.+?)(?=(?:Card Set ID:|$))"
card_set_name_pattern = r"Card Set Name: (.+?)(?=(?:Card Set Name:|$))"
card_set_series_pattern = r"Card Set Series: (.+?)(?=(?:Card Set Series:|$))"
card_set_printed_total_pattern = r"Card Set Printed Total: (.+?)(?=(?:Card Set Printed Total:|$))"
card_set_total_pattern = r"Card Set Total: (.+?)(?=(?:Card Set Total:|$))"
card_set_standard_pattern = r"Card Set Standard: (.+?)(?=(?:Card Set Standard:|$))"
card_set_expanded_pattern = r"Card Set Expanded: (.+?)(?=(?:Card Set Expanded:|$))"
card_set_unlimited_pattern = r"Card Set Unlimited: (.+?)(?=(?:Card Set Unlimited:|$))"
card_set_ptcgo_code_pattern = r"Card Set PTCGO Code: (.+?)(?=(?:Card Set PTCGO Code:|$))"
card_set_release_date_pattern = r"Card Set Release Date: (.+?)(?=(?:Card Set Release Date:|$))"
card_set_updated_at_pattern = r"Card Set Updated At: (.+?)(?=(?:Card Set Updated At:|$))"
card_set_symbol_pattern = r"Card Set Symbol: (.+?)(?=(?:Card Set Symbol:|$))"
card_set_logo_pattern = r"Card Set Logo: (.+?)(?=(?:Card Set Logo:|$))"
number_pattern = r"Number: (.+?)(?=(?:Number:|$))"
artist_pattern = r"Artist: (.+?)(?=(?:Artist:|$))"
rarity_pattern = r"Rarity: (.+?)(?=(?:Rarity:|$))"
flavor_text_pattern = r"Flavor Text: (.+?)(?=(?:Flavor Text:|$))"
national_pokedex_numbers_pattern = r"National Pokedex Numbers: (.+?)(?=(?:National Pokedex Numbers:|$))"
unlimited_pattern = r"Unlimited: (.+?)(?=(?:Unlimited:|$))"
standard_pattern = r"Standard: (.+?)(?=(?:Standard:|$))"
expanded_pattern = r"Expanded: (.+?)(?=(?:Expanded:|$))"
regulation_mark_pattern = r"Regulation Mark: (.+?)(?=(?:Regulation Mark:|$))"
small_image_pattern = r"Small Image: (.+?)(?=(?:Small Image:|$))"
large_image_pattern = r"Large Image: (.+?)(?=(?:Large Image:|$))"
